/**
 * \file parametersMapperMerger.cpp
 * \attention This file is automatically generated and should not be in general modifed manually
 *
 * \date MMM DD, 20YY
 * \author autoGenerator
 */

#include "parametersMapperMerger.h"

ParametersMapperMerger::ParametersMapperMerger() :
    mBaseParametersControlWidget(NULL)
  , mMergerControlWidget(NULL)
  , mPresentationParametersControlWidget(NULL)
{
    qRegisterMetaType<QSharedPointer<BaseParameters> >("QSharedPointer<BaseParameters>");
    qRegisterMetaType<QSharedPointer<Merger> >("QSharedPointer<Merger>");
    qRegisterMetaType<QSharedPointer<PresentationParameters> >("QSharedPointer<PresentationParameters>");
}

void ParametersMapperMerger::setBaseParametersControlWidget(BaseParametersControlWidget *widget)
{
    mBaseParametersControlWidget = widget;
    QObject::connect(mBaseParametersControlWidget, SIGNAL(paramsChanged()), this, SLOT(paramsChanged()));
}

void ParametersMapperMerger::setMergerControlWidget(MergerControlWidget *widget)
{
    mMergerControlWidget = widget;
    QObject::connect(mMergerControlWidget, SIGNAL(paramsChanged()), this, SLOT(paramsChanged()));
}

void ParametersMapperMerger::setPresentationParametersControlWidget(PresentationParametersControlWidget *widget)
{
    mPresentationParametersControlWidget = widget;
    QObject::connect(mPresentationParametersControlWidget, SIGNAL(paramsChanged()), this, SLOT(paramsChanged()));
}

void ParametersMapperMerger::paramsChanged()
{
    if (mBaseParametersControlWidget == NULL)
    {
          std::cout << "One of the fields for ParametersMapperMerger \n"
               "is still NULL but the mapper is already in use. This will cause crash.\n"
               "You should modify your <HostWidget>::createCalculator() function" << std::endl;
    }
    emit baseParametersParamsChanged(QSharedPointer<BaseParameters>(mBaseParametersControlWidget->createParameters()));


    if (mMergerControlWidget == NULL)
    {
          std::cout << "One of the fields for ParametersMapperMerger \n"
               "is still NULL but the mapper is already in use. This will cause crash.\n"
               "You should modify your <HostWidget>::createCalculator() function" << std::endl;
    }
    emit mergerParamsChanged(QSharedPointer<Merger>(mMergerControlWidget->createParameters()));


    if (mPresentationParametersControlWidget == NULL)
    {
          std::cout << "One of the fields for ParametersMapperMerger \n"
               "is still NULL but the mapper is already in use. This will cause crash.\n"
               "You should modify your <HostWidget>::createCalculator() function" << std::endl;
    }
    emit presentationParametersParamsChanged(QSharedPointer<PresentationParameters>(mPresentationParametersControlWidget->createParameters()));


}

