#ifndef MERGER_UNDIST_METHOD_H_
#define MERGER_UNDIST_METHOD_H_
/**
 * \file mergerUndistMethod.h
 * \attention This file is automatically generated and should not be in general modified manually
 *
 * \date MMM DD, 20YY
 * \author autoGenerator
 * Generated from merger.xml
 */

/**
 * Helper namespace to hide MergerUndistMethod enum from global context.
 */

namespace MergerUndistMethod {

/** 
 * \brief Merger Undist Method 
 * Merger Undist Method 
 */
enum MergerUndistMethod {
    /** 
     * \brief None 
     * None 
     */
    NONE = 0,
    /** 
     * \brief Square Table 
     * Square Table 
     */
    SQUARE_TABLE = 1,
    /** 
     * \brief Radial Table 
     * Radial Table 
     */
    RADIAL_TABLE = 2,
    /** 
     * \brief HD Table 
     * HD Table 
     */
    HD_TABLE = 3,
    /** 
     * \brief Loaded Camera 
     * Loaded Camera 
     */
    LOADED_CAMERA = 4,
    /** 
     * \brief Last virtual option to run cycles to
     */
    MERGER_UNDIST_METHOD_LAST
};


static inline const char *getName(const MergerUndistMethod &value)
{
    switch (value) 
    {
     case NONE : return "NONE"; break ;
     case SQUARE_TABLE : return "SQUARE_TABLE"; break ;
     case RADIAL_TABLE : return "RADIAL_TABLE"; break ;
     case HD_TABLE : return "HD_TABLE"; break ;
     case LOADED_CAMERA : return "LOADED_CAMERA"; break ;
     default : return "Not in range"; break ;
     
    }
    return "Not in range";
}

} //namespace MergerUndistMethod

#endif  //MERGER_UNDIST_METHOD_H_
