/**
 * \file merger.cpp
 * \attention This file is automatically generated and should not be in general modified manually
 *
 * \date MMM DD, 20YY
 * \author autoGenerator
 */

#include <vector>
#include <stddef.h>
#include "merger.h"

/**
 *  Looks extremely unsafe because it depends on the order of static initialization.
 *  Should check standard if this is ok
 *
 *  Also it's not clear why removing "= Reflection()" breaks the code;
 **/

namespace corecvs {
template<>
Reflection BaseReflection<Merger>::reflection = Reflection();
template<>
int BaseReflection<Merger>::dummy = Merger::staticInit();
} // namespace corecvs 

SUPPRESS_OFFSET_WARNING_BEGIN


using namespace corecvs;

int Merger::staticInit()
{

    ReflectionNaming &nameing = naming();
    nameing = ReflectionNaming(
        "Merger",
        "Merger parameters",
        ""
    );

     getReflection()->objectSize = sizeof(Merger);
     

    EnumField* field0 = new EnumField
        (
          Merger::UNDISTMETHOD_ID,
          offsetof(Merger, mUndistMethod),
          3,
          "undistMethod",
          "undistMethod",
          "undistMethod",
          new EnumReflection(4
          , new EnumOption(0,"None")
          , new EnumOption(1,"Square Table")
          , new EnumOption(2,"Radial Table")
          , new EnumOption(3,"HD Table")
          )
        );
    field0->widgetHint=BaseField::COMBO_BOX;
    fields().push_back(field0);
    /*  */ 
    DoubleField* field1 = new DoubleField
        (
          Merger::UNDIST_FOCAL_ID,
          offsetof(Merger, mUndistFocal),
          0.9,
          "Undist Focal",
          "Undist Focal",
          "Undist Focal",
          true,
         0,
         99999
        );
    field1->widgetHint=BaseField::SPIN_BOX;
    field1->suffixHint="mm";
    field1->precision=3;
    fields().push_back(field1);
    /*  */ 
    DoubleField* field2 = new DoubleField
        (
          Merger::MM_TO_PIXEL_ID,
          offsetof(Merger, mMMToPixel),
          400,
          "MM to Pixel",
          "MM to Pixel",
          "MM to Pixel",
          true,
         0,
         99999
        );
    field2->widgetHint=BaseField::SPIN_BOX;
    field2->suffixHint="pix";
    field2->precision=3;
    fields().push_back(field2);
    /*  */ 
    BoolField* field3 = new BoolField
        (
          Merger::SHOWMASK_ID,
          offsetof(Merger, mShowMask),
          true,
          "showMask",
          "showMask",
          "showMask"
        );
    field3->widgetHint=BaseField::CHECK_BOX;
    fields().push_back(field3);
    /*  */ 
    BoolField* field4 = new BoolField
        (
          Merger::BILINEAR_ID,
          offsetof(Merger, mBilinear),
          false,
          "bilinear",
          "bilinear",
          "bilinear"
        );
    field4->widgetHint=BaseField::CHECK_BOX;
    fields().push_back(field4);
    /*  */ 
    BoolField* field5 = new BoolField
        (
          Merger::SEPARATE_VIEW_ID,
          offsetof(Merger, mSeparateView),
          false,
          "Separate View",
          "Separate View",
          "Separate View"
        );
    field5->widgetHint=BaseField::CHECK_BOX;
    fields().push_back(field5);
    /*  */ 
    IntField* field6 = new IntField
        (
          Merger::FRAMETOUNDIST_ID,
          offsetof(Merger, mFrameToUndist),
          0,
          "frameToUndist",
          "frameToUndist",
          "frameToUndist",
          true,
         0,
         3
        );
    fields().push_back(field6);
    /*  */ 
    DoubleField* field7 = new DoubleField
        (
          Merger::OUT_SIZE_H_ID,
          offsetof(Merger, mOutSizeH),
          1000,
          "Out Size H",
          "Out Size H",
          "Out Size H",
          true,
         10,
         99999
        );
    field7->widgetHint=BaseField::SPIN_BOX;
    field7->suffixHint="px";
    field7->precision=2;
    fields().push_back(field7);
    /*  */ 
    DoubleField* field8 = new DoubleField
        (
          Merger::OUT_PHY_SIZE_L_ID,
          offsetof(Merger, mOutPhySizeL),
          200,
          "Out Phy Size L",
          "Out Phy Size L",
          "Out Phy Size L",
          true,
         1,
         99999
        );
    field8->widgetHint=BaseField::SPIN_BOX;
    field8->suffixHint="dm";
    field8->precision=2;
    fields().push_back(field8);
    /*  */ 
    DoubleField* field9 = new DoubleField
        (
          Merger::OUT_PHY_SIZE_W_ID,
          offsetof(Merger, mOutPhySizeW),
          200,
          "Out Phy Size W",
          "Out Phy Size W",
          "Out Phy Size W",
          true,
         1,
         99999
        );
    field9->widgetHint=BaseField::SPIN_BOX;
    field9->suffixHint="dm";
    field9->precision=2;
    fields().push_back(field9);
    /*  */ 
    DoubleField* field10 = new DoubleField
        (
          Merger::GROUND_Z_ID,
          offsetof(Merger, mGroundZ),
          -20,
          "ground Z",
          "ground Z",
          "ground Z",
          true,
         -99999,
         99999
        );
    field10->widgetHint=BaseField::SPIN_BOX;
    field10->precision=2;
    fields().push_back(field10);
    /*  */ 
    DoubleField* field11 = new DoubleField
        (
          Merger::FOV1_ID,
          offsetof(Merger, mFOV1),
          120,
          "FOV1",
          "FOV1",
          "FOV1",
          true,
         1,
         360
        );
    field11->widgetHint=BaseField::SPIN_BOX;
    field11->suffixHint="deg";
    field11->precision=2;
    fields().push_back(field11);
    /*  */ 
    BoolField* field12 = new BoolField
        (
          Merger::SWITCH1_ID,
          offsetof(Merger, mSwitch1),
          true,
          "switch1",
          "switch1",
          "switch1"
        );
    field12->widgetHint=BaseField::CHECK_BOX;
    fields().push_back(field12);
    /*  */ 
    CompositeField* field13 = new CompositeField
        (
          Merger::POS1_ID,
          offsetof(Merger, mPos1),
          "pos1",
          "EuclidianMoveParameters",
          "pos1",
          "pos1",
           NULL
        );
    {
        ReflectionDirectory* directory = ReflectionDirectoryHolder::getReflectionDirectory();
        std::string name("Euclidian Move Parameters");
        ReflectionDirectory::iterator it = directory->find(name);
        if(it != directory->end()) {
             field13->reflection = it->second;
        } else {
             printf("Reflection Merger to the subclass Euclidian Move Parameters can't be linked\n");
        }
    }
    fields().push_back(field13);
    /*  */ 
    DoubleField* field14 = new DoubleField
        (
          Merger::FOV2_ID,
          offsetof(Merger, mFOV2),
          120,
          "FOV2",
          "FOV2",
          "FOV2",
          true,
         1,
         360
        );
    field14->widgetHint=BaseField::SPIN_BOX;
    field14->suffixHint="deg";
    field14->precision=2;
    fields().push_back(field14);
    /*  */ 
    BoolField* field15 = new BoolField
        (
          Merger::SWITCH2_ID,
          offsetof(Merger, mSwitch2),
          true,
          "switch2",
          "switch2",
          "switch2"
        );
    field15->widgetHint=BaseField::CHECK_BOX;
    fields().push_back(field15);
    /*  */ 
    CompositeField* field16 = new CompositeField
        (
          Merger::POS2_ID,
          offsetof(Merger, mPos2),
          "pos2",
          "EuclidianMoveParameters",
          "pos2",
          "pos2",
           NULL
        );
    {
        ReflectionDirectory* directory = ReflectionDirectoryHolder::getReflectionDirectory();
        std::string name("Euclidian Move Parameters");
        ReflectionDirectory::iterator it = directory->find(name);
        if(it != directory->end()) {
             field16->reflection = it->second;
        } else {
             printf("Reflection Merger to the subclass Euclidian Move Parameters can't be linked\n");
        }
    }
    fields().push_back(field16);
    /*  */ 
    DoubleField* field17 = new DoubleField
        (
          Merger::FOV3_ID,
          offsetof(Merger, mFOV3),
          120,
          "FOV3",
          "FOV3",
          "FOV3",
          true,
         1,
         360
        );
    field17->widgetHint=BaseField::SPIN_BOX;
    field17->suffixHint="deg";
    field17->precision=2;
    fields().push_back(field17);
    /*  */ 
    BoolField* field18 = new BoolField
        (
          Merger::SWITCH3_ID,
          offsetof(Merger, mSwitch3),
          true,
          "switch3",
          "switch3",
          "switch3"
        );
    field18->widgetHint=BaseField::CHECK_BOX;
    fields().push_back(field18);
    /*  */ 
    CompositeField* field19 = new CompositeField
        (
          Merger::POS3_ID,
          offsetof(Merger, mPos3),
          "pos3",
          "EuclidianMoveParameters",
          "pos3",
          "pos3",
           NULL
        );
    {
        ReflectionDirectory* directory = ReflectionDirectoryHolder::getReflectionDirectory();
        std::string name("Euclidian Move Parameters");
        ReflectionDirectory::iterator it = directory->find(name);
        if(it != directory->end()) {
             field19->reflection = it->second;
        } else {
             printf("Reflection Merger to the subclass Euclidian Move Parameters can't be linked\n");
        }
    }
    fields().push_back(field19);
    /*  */ 
    DoubleField* field20 = new DoubleField
        (
          Merger::FOV4_ID,
          offsetof(Merger, mFOV4),
          120,
          "FOV4",
          "FOV4",
          "FOV4",
          true,
         1,
         360
        );
    field20->widgetHint=BaseField::SPIN_BOX;
    field20->suffixHint="deg";
    field20->precision=2;
    fields().push_back(field20);
    /*  */ 
    BoolField* field21 = new BoolField
        (
          Merger::SWITCH4_ID,
          offsetof(Merger, mSwitch4),
          true,
          "switch4",
          "switch4",
          "switch4"
        );
    field21->widgetHint=BaseField::CHECK_BOX;
    fields().push_back(field21);
    /*  */ 
    CompositeField* field22 = new CompositeField
        (
          Merger::POS4_ID,
          offsetof(Merger, mPos4),
          "pos4",
          "EuclidianMoveParameters",
          "pos4",
          "pos4",
           NULL
        );
    {
        ReflectionDirectory* directory = ReflectionDirectoryHolder::getReflectionDirectory();
        std::string name("Euclidian Move Parameters");
        ReflectionDirectory::iterator it = directory->find(name);
        if(it != directory->end()) {
             field22->reflection = it->second;
        } else {
             printf("Reflection Merger to the subclass Euclidian Move Parameters can't be linked\n");
        }
    }
    fields().push_back(field22);
    /*  */ 
    ReflectionDirectory &directory = *ReflectionDirectoryHolder::getReflectionDirectory();
    directory[std::string("Merger")]= &reflection;
   return 0;
}
int Merger::relinkCompositeFields()
{
    {
        ReflectionDirectory* directory = ReflectionDirectoryHolder::getReflectionDirectory();
        std::string name("Euclidian Move Parameters");
        ReflectionDirectory::iterator it = directory->find(name);
        if(it != directory->end()) {
             const CompositeField* field = static_cast<const CompositeField*>(getReflection()->fields[13]);
             const_cast<CompositeField*>(field)->reflection = it->second;
        } else {
             printf("Reflection Merger to the subclass Euclidian Move Parameters can't be linked\n");
        }
    }
    {
        ReflectionDirectory* directory = ReflectionDirectoryHolder::getReflectionDirectory();
        std::string name("Euclidian Move Parameters");
        ReflectionDirectory::iterator it = directory->find(name);
        if(it != directory->end()) {
             const CompositeField* field = static_cast<const CompositeField*>(getReflection()->fields[16]);
             const_cast<CompositeField*>(field)->reflection = it->second;
        } else {
             printf("Reflection Merger to the subclass Euclidian Move Parameters can't be linked\n");
        }
    }
    {
        ReflectionDirectory* directory = ReflectionDirectoryHolder::getReflectionDirectory();
        std::string name("Euclidian Move Parameters");
        ReflectionDirectory::iterator it = directory->find(name);
        if(it != directory->end()) {
             const CompositeField* field = static_cast<const CompositeField*>(getReflection()->fields[19]);
             const_cast<CompositeField*>(field)->reflection = it->second;
        } else {
             printf("Reflection Merger to the subclass Euclidian Move Parameters can't be linked\n");
        }
    }
    {
        ReflectionDirectory* directory = ReflectionDirectoryHolder::getReflectionDirectory();
        std::string name("Euclidian Move Parameters");
        ReflectionDirectory::iterator it = directory->find(name);
        if(it != directory->end()) {
             const CompositeField* field = static_cast<const CompositeField*>(getReflection()->fields[22]);
             const_cast<CompositeField*>(field)->reflection = it->second;
        } else {
             printf("Reflection Merger to the subclass Euclidian Move Parameters can't be linked\n");
        }
    }
   return 0;
}

SUPPRESS_OFFSET_WARNING_END


