/**
 * \file dummyProviderParameters.cpp
 * \attention This file is automatically generated and should not be in general modified manually
 *
 * \date MMM DD, 20YY
 * \author autoGenerator
 */

#include <vector>
#include <stddef.h>
#include "dummyProviderParameters.h"

/**
 *  Looks extremely unsafe because it depends on the order of static initialization.
 *  Should check standard if this is ok
 *
 *  Also it's not clear why removing "= Reflection()" breaks the code;
 **/

namespace corecvs {
template<>
Reflection BaseReflection<DummyProviderParameters>::reflection = Reflection();
template<>
int BaseReflection<DummyProviderParameters>::dummy = DummyProviderParameters::staticInit();
} // namespace corecvs 

SUPPRESS_OFFSET_WARNING_BEGIN

int DummyProviderParameters::staticInit()
{

    ReflectionNaming &nameing = naming();
    nameing = ReflectionNaming(
        "Dummy Provider Parameters",
        "Dummy Provider Parameters",
        ""
    );
     

    fields().push_back(
        new StringField
        (
          DummyProviderParameters::PATH_ID,
          offsetof(DummyProviderParameters, mPath),
          "data/pair/image%04d_c0.pgm",
          "Path",
          "Path",
          "Path"
        )
    );
    fields().push_back(
        new IntField
        (
          DummyProviderParameters::UNKNOWN_VALUE_ID,
          offsetof(DummyProviderParameters, mUnknownValue),
          0,
          "Unknown Value",
          "Unknown Value",
          "Unknown Value"
        )
    );
    fields().push_back(
        new IntField
        (
          DummyProviderParameters::PLANE_ZERO_ID,
          offsetof(DummyProviderParameters, mPlaneZero),
          0,
          "Plane Zero",
          "Plane Zero",
          "Plane Zero"
        )
    );
    fields().push_back(
        new IntField
        (
          DummyProviderParameters::PLANE_MAX_ID,
          offsetof(DummyProviderParameters, mPlaneMax),
          65536,
          "Plane Max",
          "Plane Max",
          "Plane Max"
        )
    );
   return 0;
}

SUPPRESS_OFFSET_WARNING_END


