##################################################################
#  This QMAKE PRI File was autogenerated Thu Jun 30 15:27:31 MSK 2016
##################################################################
SOURCES+= $${UTILSDIR}/corestructs/coreWidgets/rgbColorParametersControlWidget.cpp
HEADERS+= $${UTILSDIR}/corestructs/coreWidgets/rgbColorParametersControlWidget.h
FORMS += $${UTILSDIR}/corestructs/coreWidgets/rgbColorParametersControlWidget.ui

SOURCES+= $${UTILSDIR}/corestructs/coreWidgets/axisAlignedBoxParametersControlWidget.cpp
HEADERS+= $${UTILSDIR}/corestructs/coreWidgets/axisAlignedBoxParametersControlWidget.h
FORMS += $${UTILSDIR}/corestructs/coreWidgets/axisAlignedBoxParametersControlWidget.ui

SOURCES+= $${UTILSDIR}/corestructs/coreWidgets/headSearchParametersControlWidget.cpp
HEADERS+= $${UTILSDIR}/corestructs/coreWidgets/headSearchParametersControlWidget.h
FORMS += $${UTILSDIR}/corestructs/coreWidgets/headSearchParametersControlWidget.ui

SOURCES+= $${UTILSDIR}/corestructs/coreWidgets/makePreciseParametersControlWidget.cpp
HEADERS+= $${UTILSDIR}/corestructs/coreWidgets/makePreciseParametersControlWidget.h
FORMS += $${UTILSDIR}/corestructs/coreWidgets/makePreciseParametersControlWidget.ui

SOURCES+= $${UTILSDIR}/corestructs/coreWidgets/debayerParametersControlWidget.cpp
HEADERS+= $${UTILSDIR}/corestructs/coreWidgets/debayerParametersControlWidget.h
FORMS += $${UTILSDIR}/corestructs/coreWidgets/debayerParametersControlWidget.ui

SOURCES+= $${UTILSDIR}/corestructs/coreWidgets/checkerboardDetectionParametersControlWidget.cpp
HEADERS+= $${UTILSDIR}/corestructs/coreWidgets/checkerboardDetectionParametersControlWidget.h
FORMS += $${UTILSDIR}/corestructs/coreWidgets/checkerboardDetectionParametersControlWidget.ui

SOURCES+= $${UTILSDIR}/corestructs/coreWidgets/lineDistortionEstimatorParametersControlWidget.cpp
HEADERS+= $${UTILSDIR}/corestructs/coreWidgets/lineDistortionEstimatorParametersControlWidget.h
FORMS += $${UTILSDIR}/corestructs/coreWidgets/lineDistortionEstimatorParametersControlWidget.ui

SOURCES+= $${UTILSDIR}/corestructs/coreWidgets/distortionApplicationParametersControlWidget.cpp
HEADERS+= $${UTILSDIR}/corestructs/coreWidgets/distortionApplicationParametersControlWidget.h
FORMS += $${UTILSDIR}/corestructs/coreWidgets/distortionApplicationParametersControlWidget.ui

SOURCES+= $${UTILSDIR}/corestructs/coreWidgets/chessBoardCornerDetectorParamsBaseControlWidget.cpp
HEADERS+= $${UTILSDIR}/corestructs/coreWidgets/chessBoardCornerDetectorParamsBaseControlWidget.h
FORMS += $${UTILSDIR}/corestructs/coreWidgets/chessBoardCornerDetectorParamsBaseControlWidget.ui

SOURCES+= $${UTILSDIR}/corestructs/coreWidgets/chessBoardAssemblerParamsBaseControlWidget.cpp
HEADERS+= $${UTILSDIR}/corestructs/coreWidgets/chessBoardAssemblerParamsBaseControlWidget.h
FORMS += $${UTILSDIR}/corestructs/coreWidgets/chessBoardAssemblerParamsBaseControlWidget.ui

SOURCES+= $${UTILSDIR}/corestructs/coreWidgets/bitcodeBoardParamsBaseControlWidget.cpp
HEADERS+= $${UTILSDIR}/corestructs/coreWidgets/bitcodeBoardParamsBaseControlWidget.h
FORMS += $${UTILSDIR}/corestructs/coreWidgets/bitcodeBoardParamsBaseControlWidget.ui

SOURCES+= $${UTILSDIR}/corestructs/coreWidgets/iterativeReconstructionInitializationParamsControlWidget.cpp
HEADERS+= $${UTILSDIR}/corestructs/coreWidgets/iterativeReconstructionInitializationParamsControlWidget.h
FORMS += $${UTILSDIR}/corestructs/coreWidgets/iterativeReconstructionInitializationParamsControlWidget.ui

SOURCES+= $${UTILSDIR}/corestructs/coreWidgets/iterativeReconstructionFeatureSelectionParamsControlWidget.cpp
HEADERS+= $${UTILSDIR}/corestructs/coreWidgets/iterativeReconstructionFeatureSelectionParamsControlWidget.h
FORMS += $${UTILSDIR}/corestructs/coreWidgets/iterativeReconstructionFeatureSelectionParamsControlWidget.ui

SOURCES+= $${UTILSDIR}/corestructs/coreWidgets/iterativeReconstructionAppendParamsControlWidget.cpp
HEADERS+= $${UTILSDIR}/corestructs/coreWidgets/iterativeReconstructionAppendParamsControlWidget.h
FORMS += $${UTILSDIR}/corestructs/coreWidgets/iterativeReconstructionAppendParamsControlWidget.ui

SOURCES+= $${UTILSDIR}/corestructs/coreWidgets/iterativeReconstructionNonlinearOptimizationParamsWrapperControlWidget.cpp
HEADERS+= $${UTILSDIR}/corestructs/coreWidgets/iterativeReconstructionNonlinearOptimizationParamsWrapperControlWidget.h
FORMS += $${UTILSDIR}/corestructs/coreWidgets/iterativeReconstructionNonlinearOptimizationParamsWrapperControlWidget.ui

SOURCES+= $${UTILSDIR}/corestructs/coreWidgets/featureDetectionParamsControlWidget.cpp
HEADERS+= $${UTILSDIR}/corestructs/coreWidgets/featureDetectionParamsControlWidget.h
FORMS += $${UTILSDIR}/corestructs/coreWidgets/featureDetectionParamsControlWidget.ui

SOURCES+= $${UTILSDIR}/corestructs/coreWidgets/reconstructionFunctorOptimizationParamsControlWidget.cpp
HEADERS+= $${UTILSDIR}/corestructs/coreWidgets/reconstructionFunctorOptimizationParamsControlWidget.h
FORMS += $${UTILSDIR}/corestructs/coreWidgets/reconstructionFunctorOptimizationParamsControlWidget.ui

