##################################################################
#  This QMAKE PRI File was autogenerated Пт. мая 20 17:18:21 MSK 2016
##################################################################
SOURCES+= $${UTILSDIR}/corestructs/coreWidgets/rgbColorParametersControlWidget.cpp
HEADERS+= $${UTILSDIR}/corestructs/coreWidgets/rgbColorParametersControlWidget.h
FORMS += $${UTILSDIR}/corestructs/coreWidgets/rgbColorParametersControlWidget.ui

SOURCES+= $${UTILSDIR}/corestructs/coreWidgets/axisAlignedBoxParametersControlWidget.cpp
HEADERS+= $${UTILSDIR}/corestructs/coreWidgets/axisAlignedBoxParametersControlWidget.h
FORMS += $${UTILSDIR}/corestructs/coreWidgets/axisAlignedBoxParametersControlWidget.ui

SOURCES+= $${UTILSDIR}/corestructs/coreWidgets/headSearchParametersControlWidget.cpp
HEADERS+= $${UTILSDIR}/corestructs/coreWidgets/headSearchParametersControlWidget.h
FORMS += $${UTILSDIR}/corestructs/coreWidgets/headSearchParametersControlWidget.ui

SOURCES+= $${UTILSDIR}/corestructs/coreWidgets/makePreciseParametersControlWidget.cpp
HEADERS+= $${UTILSDIR}/corestructs/coreWidgets/makePreciseParametersControlWidget.h
FORMS += $${UTILSDIR}/corestructs/coreWidgets/makePreciseParametersControlWidget.ui

SOURCES+= $${UTILSDIR}/corestructs/coreWidgets/debayerParametersControlWidget.cpp
HEADERS+= $${UTILSDIR}/corestructs/coreWidgets/debayerParametersControlWidget.h
FORMS += $${UTILSDIR}/corestructs/coreWidgets/debayerParametersControlWidget.ui

SOURCES+= $${UTILSDIR}/corestructs/coreWidgets/checkerboardDetectionParametersControlWidget.cpp
HEADERS+= $${UTILSDIR}/corestructs/coreWidgets/checkerboardDetectionParametersControlWidget.h
FORMS += $${UTILSDIR}/corestructs/coreWidgets/checkerboardDetectionParametersControlWidget.ui

SOURCES+= $${UTILSDIR}/corestructs/coreWidgets/lineDistortionEstimatorParametersControlWidget.cpp
HEADERS+= $${UTILSDIR}/corestructs/coreWidgets/lineDistortionEstimatorParametersControlWidget.h
FORMS += $${UTILSDIR}/corestructs/coreWidgets/lineDistortionEstimatorParametersControlWidget.ui

SOURCES+= $${UTILSDIR}/corestructs/coreWidgets/distortionApplicationParametersControlWidget.cpp
HEADERS+= $${UTILSDIR}/corestructs/coreWidgets/distortionApplicationParametersControlWidget.h
FORMS += $${UTILSDIR}/corestructs/coreWidgets/distortionApplicationParametersControlWidget.ui

SOURCES+= $${UTILSDIR}/corestructs/coreWidgets/chessBoardCornerDetectorParamsBaseControlWidget.cpp
HEADERS+= $${UTILSDIR}/corestructs/coreWidgets/chessBoardCornerDetectorParamsBaseControlWidget.h
FORMS += $${UTILSDIR}/corestructs/coreWidgets/chessBoardCornerDetectorParamsBaseControlWidget.ui

SOURCES+= $${UTILSDIR}/corestructs/coreWidgets/chessBoardAssemblerParamsBaseControlWidget.cpp
HEADERS+= $${UTILSDIR}/corestructs/coreWidgets/chessBoardAssemblerParamsBaseControlWidget.h
FORMS += $${UTILSDIR}/corestructs/coreWidgets/chessBoardAssemblerParamsBaseControlWidget.ui

SOURCES+= $${UTILSDIR}/corestructs/coreWidgets/bitcodeBoardParamsBaseControlWidget.cpp
HEADERS+= $${UTILSDIR}/corestructs/coreWidgets/bitcodeBoardParamsBaseControlWidget.h
FORMS += $${UTILSDIR}/corestructs/coreWidgets/bitcodeBoardParamsBaseControlWidget.ui

SOURCES+= $${UTILSDIR}/corestructs/coreWidgets/photostationPlacerParamsBaseControlWidget.cpp
HEADERS+= $${UTILSDIR}/corestructs/coreWidgets/photostationPlacerParamsBaseControlWidget.h
FORMS += $${UTILSDIR}/corestructs/coreWidgets/photostationPlacerParamsBaseControlWidget.ui

SOURCES+= $${UTILSDIR}/corestructs/coreWidgets/photostationPlacerEssentialFilterParametersControlWidget.cpp
HEADERS+= $${UTILSDIR}/corestructs/coreWidgets/photostationPlacerEssentialFilterParametersControlWidget.h
FORMS += $${UTILSDIR}/corestructs/coreWidgets/photostationPlacerEssentialFilterParametersControlWidget.ui

SOURCES+= $${UTILSDIR}/corestructs/coreWidgets/photostationPlacerFeatureSelectionParametersControlWidget.cpp
HEADERS+= $${UTILSDIR}/corestructs/coreWidgets/photostationPlacerFeatureSelectionParametersControlWidget.h
FORMS += $${UTILSDIR}/corestructs/coreWidgets/photostationPlacerFeatureSelectionParametersControlWidget.ui

SOURCES+= $${UTILSDIR}/corestructs/coreWidgets/photostationAppendParametersControlWidget.cpp
HEADERS+= $${UTILSDIR}/corestructs/coreWidgets/photostationAppendParametersControlWidget.h
FORMS += $${UTILSDIR}/corestructs/coreWidgets/photostationAppendParametersControlWidget.ui

SOURCES+= $${UTILSDIR}/corestructs/coreWidgets/photostationNonlinearOptimizationParametersControlWidget.cpp
HEADERS+= $${UTILSDIR}/corestructs/coreWidgets/photostationNonlinearOptimizationParametersControlWidget.h
FORMS += $${UTILSDIR}/corestructs/coreWidgets/photostationNonlinearOptimizationParametersControlWidget.ui

SOURCES+= $${UTILSDIR}/corestructs/coreWidgets/iterativeReconstructionInitializationParamsControlWidget.cpp
HEADERS+= $${UTILSDIR}/corestructs/coreWidgets/iterativeReconstructionInitializationParamsControlWidget.h
FORMS += $${UTILSDIR}/corestructs/coreWidgets/iterativeReconstructionInitializationParamsControlWidget.ui

SOURCES+= $${UTILSDIR}/corestructs/coreWidgets/iterativeReconstructionFeatureSelectionParamsControlWidget.cpp
HEADERS+= $${UTILSDIR}/corestructs/coreWidgets/iterativeReconstructionFeatureSelectionParamsControlWidget.h
FORMS += $${UTILSDIR}/corestructs/coreWidgets/iterativeReconstructionFeatureSelectionParamsControlWidget.ui

SOURCES+= $${UTILSDIR}/corestructs/coreWidgets/iterativeReconstructionAppendParamsControlWidget.cpp
HEADERS+= $${UTILSDIR}/corestructs/coreWidgets/iterativeReconstructionAppendParamsControlWidget.h
FORMS += $${UTILSDIR}/corestructs/coreWidgets/iterativeReconstructionAppendParamsControlWidget.ui

SOURCES+= $${UTILSDIR}/corestructs/coreWidgets/iterativeReconstructionNonlinearOptimizationParamsControlWidget.cpp
HEADERS+= $${UTILSDIR}/corestructs/coreWidgets/iterativeReconstructionNonlinearOptimizationParamsControlWidget.h
FORMS += $${UTILSDIR}/corestructs/coreWidgets/iterativeReconstructionNonlinearOptimizationParamsControlWidget.ui

SOURCES+= $${UTILSDIR}/corestructs/coreWidgets/featureDetectionParamsControlWidget.cpp
HEADERS+= $${UTILSDIR}/corestructs/coreWidgets/featureDetectionParamsControlWidget.h
FORMS += $${UTILSDIR}/corestructs/coreWidgets/featureDetectionParamsControlWidget.ui

SOURCES+= $${UTILSDIR}/corestructs/coreWidgets/reconstructionFunctorOptimizationParamsControlWidget.cpp
HEADERS+= $${UTILSDIR}/corestructs/coreWidgets/reconstructionFunctorOptimizationParamsControlWidget.h
FORMS += $${UTILSDIR}/corestructs/coreWidgets/reconstructionFunctorOptimizationParamsControlWidget.ui

