/**
 * \file projectionBaseParametersControlWidget.cpp
 * \attention This file is automatically generated and should not be in general modified manually
 *
 * \date MMM DD, 20YY
 * \author autoGenerator
 */

#include "projectionBaseParametersControlWidget.h"
#include "ui_projectionBaseParametersControlWidget.h"
#include <memory>
#include "qSettingsGetter.h"
#include "qSettingsSetter.h"


ProjectionBaseParametersControlWidget::ProjectionBaseParametersControlWidget(QWidget *parent, bool _autoInit, QString _rootPath)
    : ParametersControlWidgetBase(parent)
    , mUi(new Ui::ProjectionBaseParametersControlWidget)
    , autoInit(_autoInit)
    , rootPath(_rootPath)
{
    mUi->setupUi(this);

    QObject::connect(mUi->principalXSpinBox, SIGNAL(valueChanged(double)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->principalYSpinBox, SIGNAL(valueChanged(double)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->focalSpinBox, SIGNAL(valueChanged(double)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->sizeXSpinBox, SIGNAL(valueChanged(double)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->sizeYSpinBox, SIGNAL(valueChanged(double)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->distortedSizeXSpinBox, SIGNAL(valueChanged(double)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->distortedSizeYSpinBox, SIGNAL(valueChanged(double)), this, SIGNAL(paramsChanged()));
}

ProjectionBaseParametersControlWidget::~ProjectionBaseParametersControlWidget()
{

    delete mUi;
}

void ProjectionBaseParametersControlWidget::loadParamWidget(WidgetLoader &loader)
{
    std::unique_ptr<ProjectionBaseParameters> params(createParameters());
    loader.loadParameters(*params, rootPath);
    setParameters(*params);
}

void ProjectionBaseParametersControlWidget::saveParamWidget(WidgetSaver  &saver)
{
    saver.saveParameters(*std::unique_ptr<ProjectionBaseParameters>(createParameters()), rootPath);
}

void ProjectionBaseParametersControlWidget::getParameters(ProjectionBaseParameters& params) const
{
    params = *std::unique_ptr<ProjectionBaseParameters>(createParameters());
}


ProjectionBaseParameters *ProjectionBaseParametersControlWidget::createParameters() const
{

    /**
     * We should think of returning parameters by value or saving them in a preallocated place
     **/


    return new ProjectionBaseParameters(
          mUi->principalXSpinBox->value()
        , mUi->principalYSpinBox->value()
        , mUi->focalSpinBox->value()
        , mUi->sizeXSpinBox->value()
        , mUi->sizeYSpinBox->value()
        , mUi->distortedSizeXSpinBox->value()
        , mUi->distortedSizeYSpinBox->value()
    );
}

void ProjectionBaseParametersControlWidget::setParameters(const ProjectionBaseParameters &input)
{
    // Block signals to send them all at once
    bool wasBlocked = blockSignals(true);
    mUi->principalXSpinBox->setValue(input.principalX());
    mUi->principalYSpinBox->setValue(input.principalY());
    mUi->focalSpinBox->setValue(input.focal());
    mUi->sizeXSpinBox->setValue(input.sizeX());
    mUi->sizeYSpinBox->setValue(input.sizeY());
    mUi->distortedSizeXSpinBox->setValue(input.distortedSizeX());
    mUi->distortedSizeYSpinBox->setValue(input.distortedSizeY());
    blockSignals(wasBlocked);
    emit paramsChanged();
}

void ProjectionBaseParametersControlWidget::setParametersVirtual(void *input)
{
    // Modify widget parameters from outside
    ProjectionBaseParameters *inputCasted = static_cast<ProjectionBaseParameters *>(input);
    setParameters(*inputCasted);
}
