/**
 * \file vector3dParametersControlWidget.cpp
 * \attention This file is automatically generated and should not be in general modified manually
 *
 * \date MMM DD, 20YY
 * \author autoGenerator
 */

#include "vector3dParametersControlWidget.h"
#include "ui_vector3dParametersControlWidget.h"
#include <memory>
#include "qSettingsGetter.h"
#include "qSettingsSetter.h"


Vector3dParametersControlWidget::Vector3dParametersControlWidget(QWidget *parent, bool _autoInit, QString _rootPath)
    : ParametersControlWidgetBase(parent)
    , mUi(new Ui::Vector3dParametersControlWidget)
    , autoInit(_autoInit)
    , rootPath(_rootPath)
{
    mUi->setupUi(this);

    QObject::connect(mUi->xSpinBox, SIGNAL(valueChanged(double)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->ySpinBox, SIGNAL(valueChanged(double)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->zSpinBox, SIGNAL(valueChanged(double)), this, SIGNAL(paramsChanged()));
}

Vector3dParametersControlWidget::~Vector3dParametersControlWidget()
{

    delete mUi;
}

void Vector3dParametersControlWidget::loadParamWidget(WidgetLoader &loader)
{
    std::unique_ptr<Vector3dParameters> params(createParameters());
    loader.loadParameters(*params, rootPath);
    setParameters(*params);
}

void Vector3dParametersControlWidget::saveParamWidget(WidgetSaver  &saver)
{
    saver.saveParameters(*std::unique_ptr<Vector3dParameters>(createParameters()), rootPath);
}

void Vector3dParametersControlWidget::getParameters(Vector3dParameters& params) const
{
    params = *std::unique_ptr<Vector3dParameters>(createParameters());
}


Vector3dParameters *Vector3dParametersControlWidget::createParameters() const
{

    /**
     * We should think of returning parameters by value or saving them in a preallocated place
     **/


    return new Vector3dParameters(
          mUi->xSpinBox->value()
        , mUi->ySpinBox->value()
        , mUi->zSpinBox->value()
    );
}

void Vector3dParametersControlWidget::setParameters(const Vector3dParameters &input)
{
    // Block signals to send them all at once
    bool wasBlocked = blockSignals(true);
    mUi->xSpinBox->setValue(input.x());
    mUi->ySpinBox->setValue(input.y());
    mUi->zSpinBox->setValue(input.z());
    blockSignals(wasBlocked);
    emit paramsChanged();
}

void Vector3dParametersControlWidget::setParametersVirtual(void *input)
{
    // Modify widget parameters from outside
    Vector3dParameters *inputCasted = static_cast<Vector3dParameters *>(input);
    setParameters(*inputCasted);
}
