/**
 * \file mergerControlWidget.cpp
 * \attention This file is automatically generated and should not be in general modified manually
 *
 * \date MMM DD, 20YY
 * \author autoGenerator
 */

#include "mergerControlWidget.h"
#include "ui_mergerControlWidget.h"
#include <memory>
#include "qSettingsGetter.h"
#include "qSettingsSetter.h"


MergerControlWidget::MergerControlWidget(QWidget *parent, bool _autoInit, QString _rootPath)
    : ParametersControlWidgetBase(parent)
    , mUi(new Ui::MergerControlWidget)
    , autoInit(_autoInit)
    , rootPath(_rootPath)
{
    mUi->setupUi(this);

    QObject::connect(mUi->pathEdit, SIGNAL(textChanged(QString)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->fileTemplateEdit, SIGNAL(textChanged(QString)), this, SIGNAL(paramsChanged()));
}

MergerControlWidget::~MergerControlWidget()
{

    delete mUi;
}

void MergerControlWidget::loadParamWidget(WidgetLoader &loader)
{
    std::unique_ptr<Merger> params(createParameters());
    loader.loadParameters(*params, rootPath);
    setParameters(*params);
}

void MergerControlWidget::saveParamWidget(WidgetSaver  &saver)
{
    saver.saveParameters(*std::unique_ptr<Merger>(createParameters()), rootPath);
}

void MergerControlWidget::getParameters(Merger& params) const
{
    params = *std::unique_ptr<Merger>(createParameters());
}


Merger *MergerControlWidget::createParameters() const
{

    /**
     * We should think of returning parameters by value or saving them in a preallocated place
     **/


    return new Merger(
          mUi->pathEdit->text().toStdString()
        , mUi->fileTemplateEdit->text().toStdString()
    );
}

void MergerControlWidget::setParameters(const Merger &input)
{
    // Block signals to send them all at once
    bool wasBlocked = blockSignals(true);
    mUi->pathEdit->setText(QString::fromStdString(input.path()));
    mUi->fileTemplateEdit->setText(QString::fromStdString(input.fileTemplate()));
    blockSignals(wasBlocked);
    emit paramsChanged();
}

void MergerControlWidget::setParametersVirtual(void *input)
{
    // Modify widget parameters from outside
    Merger *inputCasted = static_cast<Merger *>(input);
    setParameters(*inputCasted);
}
