/**
 * \file mergerWidget.cpp
 * \attention This file is automatically generated and should not be in general modified manually
 *
 * \date MMM DD, 20YY
 * \author autoGenerator
 */

#include "mergerWidget.h"
#include "ui_mergerWidget.h"
#include "qSettingsGetter.h"
#include "qSettingsSetter.h"

MergerWidget::MergerWidget(QWidget *parent)
    : QWidget(parent)
    , mUi(new Ui::MergerWidget)
{
    mUi->setupUi(this);

    Merger *params = createParameters();
    SettingsGetter visitor("cvs.conf");
    params->accept<SettingsGetter>(visitor);
    setParameters(*params);
    delete params;

    QObject::connect(mUi->pathEdit, SIGNAL(textEdited(QString)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->fileTemplateEdit, SIGNAL(textEdited(QString)), this, SIGNAL(paramsChanged()));
}

MergerWidget::~MergerWidget()
{
    Merger *params = createParameters();
    SettingsSetter visitor("cvs.conf");
    params->accept<SettingsSetter>(visitor);
    setParameters(*params);
    delete params;

    delete mUi;
}

Merger *MergerWidget::createParameters() const
{
    return new Merger(
          mUi->pathEdit->text().toStdString()
        , mUi->fileTemplateEdit->text().toStdString()
    );
}

void MergerWidget::setParameters(const Merger &input)
{
    mUi->pathEdit->setText(input.path().c_str());
    mUi->fileTemplateEdit->setText(input.fileTemplate().c_str());
}
